source_rules:
  - path: /home/ubuntu/shot-glass
    include: "LICENSE|README\\.md"
    exclude: "/\\.|docker"
  - path: /home/ubuntu/shot-glass/python/shot_glass
    include: "\\.py$"
  - path: /home/ubuntu/shot-glass/docker/config
    include: "flake8|prod.lock"
    exclude: "cache|__pypackages__"
  - path: /home/ubuntu/shot-glass/resources
    include: ".*"
    exclude: "__pycache__"
rename_rules:
  - regex: "/home/ubuntu/shot-glass"
    replace: "/home/ubuntu/build/repo"
  - regex: ".*/resources"
    replace: "/home/ubuntu/build/resources"
  - regex: "/python|/docker|/config"
    replace: ""
  - regex: "prod.lock"
    replace: "pdm.lock"
group_rules:
  - name: test
    regex: "(__init__|_test)\\.py$|flake8\\.ini$|resources|\\.lock$"
  - name: prod
    regex: "__init__\\.py$"
line_rules:
  - group: prod
    exclude: test
