version: "3.8"
services:
  shot-glass:
    container_name: shot-glass
    image: shot-glass:dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "2100:9000"
      - "2180:8080"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
    volumes:
      - ../:/home/ubuntu/shot-glass
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
